language: python

python:
    - "3.3"
    - "3.4"

script:
    - pip install pytest-asyncio
    - python setup.py test

after_success:
    - pip install coveralls
    - coveralls

branches:
  only:
    - master

notifications:
    email: false
